[package]
name = "builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatgeobuf = "4.0"
geojson = "0.24"
osmpbf = "0.3"
serde_json = "1.0"
