[package]
name = "builder"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
geo-types = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
geojson = { workspace = true }
geozero = { workspace = true }
